@host=http://localhost:5221

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMzBjN2Q2NS04NjYwLTQzOGEtYmFhNy1hYjBjZmU5NmMyNDMiLCJnaXZlbl9uYW1lIjoiTHVpZ2kiLCJmYW1pbHlfbmFtZSI6IkFsYXZleiIsImp0aSI6IjNiOTkxNWI3LWE5M2MtNDRjYy1hOWU5LTA5M2Y4NTRhZGVjNSIsImV4cCI6MTcwMTIwNzk1MCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.0Yfn9pZ13NQnGH4xBOM61fgIygtJgTaANVFa7mMF8UM